var xmlData,MOBList=null,ResultAry=[],ContentDisplayCount=10,CreateCount=1;$(document).ready(function(){if(httpObj=createXMLHttpRequest(LoadingData))httpObj.open("GET","MonsterList.xml",!0),httpObj.send(null)});function createXMLHttpRequest(b){var c=null;try{c=new XMLHttpRequest}catch(a){try{c=new ActiveXObject("Msxml2.XMLHTTP")}catch(e){try{c=new ActiveXObject("Microsoft.XMLHTTP")}catch(d){return null}}}c&&(c.onreadystatechange=b);return c}
function LoadingData(){if(4==httpObj.readyState&&200==httpObj.status){xmlData=httpObj.responseXML;MOBList=$(xmlData).find("Monster").each(function(){return $(this)});$("#status").empty().append('<font color="#FFFFFF">OK</font>');var b=$.getUrlVar("Mode");SearchOfKeyword(b);DisplayDataAry(0)}else $("#status").empty().append('<font color="#FFFFFF">Now Loading...</font>')}
$.extend({getUrlVars:function(){var b=[],c,a;a=-1==window.location.href.indexOf("#")?window.location.href.slice(window.location.href.indexOf("?")+1).split("&"):window.location.href.slice(window.location.href.indexOf("?")+1,window.location.href.indexOf("#")).split("&");for(var e=0;e<a.length;e++)c=a[e].split("="),b.push(c[0]),b[c[0]]=decodeURI(c[1]);return b},getUrlVar:function(b){return $.getUrlVars()[b]}});
function SearchOfKeyword(b){ResultAry.length=0;if(1==b){var c=$.getUrlVar("type"),a=$.getUrlVar("Lin");if(c.length&&a.length){var e=0;$(xmlData).find("Monster").each(function(){var b=$(this).find("Species").text(),d=$(this).find("Lineage").text();-1!=b.indexOf(c,0)&&-1!=d.indexOf(a,0)&&(b=$(this).attr("id"),ResultAry[e++]=b)})}}else if(2==b){var d=$.getUrlVar("keyword");d.length&&(e=0,$(xmlData).find("Monster").each(function(){if(-1!=$(this).find("MonsterName").text().indexOf(d,0)){var a=$(this).attr("id");
ResultAry[e++]=a}}))}else 3==b?(d=document.searchform1.keyword.value,d.length&&(e=0,$(xmlData).find("Monster").each(function(){if(-1!=$(this).find("MonsterName").text().indexOf(d,0)){var a=$(this).attr("id");ResultAry[e++]=a}}))):4==b&&(d=$.getUrlVar("keyword"),d.length&&(e=0,$(xmlData).find("Monster").each(function(){if(-1!=$(this).find("MonsterSkill").text().indexOf(d,0)){var a=$(this).attr("id");ResultAry[e++]=a}})))}
function DisplayDataAry(b){var c=0,a=0;CreatepIndex("pheader",b);CreatepIndex("pfooter",b);CreateTable(ContentDisplayCount);SetString(ContentDisplayCount);if(ResultAry.length){for(var c=b*ContentDisplayCount+1,e=0;e<ContentDisplayCount;e++){var d=e+b*ContentDisplayCount;d<ResultAry.length&&(a=d+1,SettingData(ResultAry[d],e))}$("#s_result").empty().append(ResultAry.length+"\u4ef6\u306e\u30e2\u30f3\u30b9\u30bf\u30fc\u304c\u8a72\u5f53\u3057\u307e\u3057\u305f\u3002  "+c+"\u4ef6\u76ee\u304b\u3089"+a+"\u4ef6\u76ee\u307e\u3067\u306e\u8868\u793a")}else $("#s_result").empty().append("\u8a72\u5f53\u30e2\u30f3\u30b9\u30bf\u30fc\u306f\u3042\u308a\u307e\u305b\u3093\u3067\u3057\u305f\u3002")}
function SettingData(b,c){var a;a=$("#tmain"+c);a.css({display:"block"});var e=$(MOBList[b]);a=$("#tmain"+c+"flv");a.attr("name",b);var d=e.find("MonsterName").text();a=$("#tmain"+c+"name");a.text(d).attr("title",b);d=e.find("Species").text();0==d&&(d="\u30a2\u30f3\u30c7\u30c3\u30c9\u578b");1==d&&(d="\u4eba\u9593\u578b");2==d&&(d="\u60aa\u9b54\u578b");3==d&&(d="\u52d5\u7269\u578b");4==d&&(d="\u795e\u7363\u578b");a=$("#tmain"+c+"fty0");a.val(d);d=e.find("Lineage").text();0==d&&(d="\u4e00\u822c1");
1==d&&(d="\u4e00\u822c2");2==d&&(d="\u4e00\u822c3");3==d&&(d="\u4e00\u822c4");4==d&&(d="\u30bb\u30df\u30dc\u30b91");5==d&&(d="\u30bb\u30df\u30dc\u30b92");6==d&&(d="\u30bb\u30df\u30dc\u30b93");7==d&&(d="\u30dc\u30b91");8==d&&(d="\u30dc\u30b92");9==d&&(d="\u30dc\u30b93");a=$("#tmain"+c+"fty1");a.val(d);d=e.find("EffectId").text();d="./MonsterImage/"+d+".png";a=$("#tmain"+c+"image");a.append($("<img />").attr({src:d,alt:"NoImage"}));d=e.find("MonsterSkill").text();a=$("#tmain"+c+"skill");a.append($("<br />")).append($("<p />").css({margin:"5px 3px",
color:"#FFFFFF"}).append(d));e=e.find("DropItemType").text();a=$("#tmain"+c+"dtype");a.append($("<br />")).append($("<p />").css({margin:"5px 3px",color:"#FFFFFF"}).append(e));StatusUpdate("tmain"+c,b)}
function StatusUpdate(b,c){var a=$(MOBList[c]),e=$("#"+b+"flv").val(),e=""===e?1:parseFloat(e),d=parseFloat(a.find("DefaultHP").text())/100,l=parseFloat(a.find("LevelUpBonus").text())/10,i=parseFloat(a.find("ConditionBonus").text())/10,h=parseFloat(a.find("STR").text())*parseFloat(a.find("StatusFactor").text())/1E5,j=parseFloat(a.find("AGI").text())*parseFloat(a.find("StatusFactor").text())/1E5,k=parseFloat(a.find("CON").text())*parseFloat(a.find("StatusFactor").text())/1E5,m=parseFloat(a.find("INT").text())*
parseFloat(a.find("StatusFactor").text())/1E5,f=parseFloat(a.find("WIS").text())*parseFloat(a.find("StatusFactor").text())/1E5,g=parseFloat(a.find("CHS").text())*parseFloat(a.find("StatusFactor").text())/1E5,n=parseFloat(a.find("LUC").text())*parseFloat(a.find("StatusFactor").text())/1E5,o=parseFloat(a.find("AtcMinValueBonus").text())/100,p=parseFloat(a.find("AtcMaxValueBonus").text())/100,q=parseFloat(a.find("DefenseValueBonus").text())/100,r=parseFloat(a.find("AtcSpeed").text())/100,s=parseFloat(a.find("MovSpeed").text()),
h=Math.floor(h*(e-1)+parseFloat(a.find("STR").text())),j=Math.floor(j*(e-1)+parseFloat(a.find("AGI").text())),k=Math.floor(k*(e-1)+parseFloat(a.find("CON").text())),m=Math.floor(m*(e-1)+parseFloat(a.find("INT").text())),f=Math.floor(f*(e-1)+parseFloat(a.find("WIS").text())),g=Math.floor(g*(e-1)+parseFloat(a.find("CHS").text())),n=Math.floor(n*(e-1)+parseFloat(a.find("LUC").text())),d=Math.floor(l*e+d+i*k),o=Math.floor((o*(e-1)+parseFloat(a.find("AtcMinValue").text()))*(1+h/200)),p=Math.floor((p*(e-
1)+parseFloat(a.find("AtcMaxValue").text()))*(1+h/200)),q=Math.floor((q*(e-1)+parseFloat(a.find("DefenseValue").text()))*(1+k/100)),l=Math.floor(parseFloat(a.find("FireResistance").text())+f/20),i=Math.floor(parseFloat(a.find("WaterResistance").text())+f/20),t=Math.floor(parseFloat(a.find("WindResistance").text())+f/20),u=Math.floor(parseFloat(a.find("EarthResistance").text())+f/20),v=Math.floor(parseFloat(a.find("LightResistance").text())+f/20),w=Math.floor(parseFloat(a.find("DarkResistance").text())+
f/20),x=Math.floor(parseFloat(a.find("Resistance1").text())+parseFloat(a.find("Resistance10").text())*((f+g)/1E3)),y=Math.floor(parseFloat(a.find("Resistance2").text())+parseFloat(a.find("Resistance10").text())*((f+g)/1E3)),z=Math.floor(parseFloat(a.find("Resistance3").text())+parseFloat(a.find("Resistance10").text())*((f+g)/1E3)),A=Math.floor(parseFloat(a.find("Resistance4").text())+parseFloat(a.find("Resistance10").text())*((f+g)/1E3)),B=Math.floor(parseFloat(a.find("Resistance5").text())+parseFloat(a.find("Resistance10").text())*
((f+g)/1E3)),C=Math.floor(parseFloat(a.find("Resistance6").text())+parseFloat(a.find("Resistance10").text())*((f+g)/1E3)),D=Math.floor(parseFloat(a.find("Resistance7").text())+parseFloat(a.find("Resistance10").text())*((f+g)/1E3)),E=Math.floor(parseFloat(a.find("Resistance8").text())+parseFloat(a.find("Resistance10").text())*((f+g)/1E3)),F=Math.floor(parseFloat(a.find("Resistance9").text())+parseFloat(a.find("Resistance10").text())*((f+g)/1E3)),G=Math.floor(parseFloat(a.find("Resistance10").text())*
(1+(f+g)/500)),H=Math.floor(parseFloat(a.find("Resistance11").text())*(1+(f+g)/1E3)),I=Math.floor(parseFloat(a.find("Resistance12").text())*(1+(f+g)/1E3)),J=Math.floor(parseFloat(a.find("Resistance13").text())*(1+(f+g)/1E3)),K=Math.floor(parseFloat(a.find("Resistance14").text())*(1+(f+g)/1E3)),L=parseInt(a.find("ActiveRange").text()),M=parseInt(a.find("Blocking").text()),e=Math.floor(parseFloat(a.find("DefaultExp").text())/10*(e+4));$("#"+b+"fab1_0").val(d);$("#"+b+"fab1_1").val(o+"~"+p);$("#"+b+
"fab1_2").val(q);$("#"+b+"fab2_0").val(r);$("#"+b+"fab2_1").val(s);$("#"+b+"fab2_2").val(M);$("#"+b+"fab2_3").val(L);$("#"+b+"fab2_4").val(e);$("#"+b+"fst0").val(h);$("#"+b+"fst1").val(j);$("#"+b+"fst2").val(k);$("#"+b+"fst3").val(m);$("#"+b+"fst4").val(f);$("#"+b+"fst5").val(g);$("#"+b+"fst6").val(n);$("#"+b+"fel0").val(l);$("#"+b+"fel1").val(i);$("#"+b+"fel2").val(t);$("#"+b+"fel3").val(u);$("#"+b+"fel4").val(v);$("#"+b+"fel5").val(w);$("#"+b+"freg1_0").val(parseInt(a.find("Resistance1").text()));
$("#"+b+"freg1_1").val(parseInt(a.find("Resistance2").text()));$("#"+b+"freg1_2").val(parseInt(a.find("Resistance3").text()));$("#"+b+"freg1_3").val(parseInt(a.find("Resistance4").text()));$("#"+b+"freg1_4").val(parseInt(a.find("Resistance5").text()));$("#"+b+"freg1_5").val(parseInt(a.find("Resistance6").text()));$("#"+b+"freg1_6").val(parseInt(a.find("Resistance7").text()));$("#"+b+"freg1_7").val(parseInt(a.find("Resistance8").text()));$("#"+b+"freg1_8").val(parseInt(a.find("Resistance9").text()));
$("#"+b+"freg1_9").val(parseInt(a.find("Resistance10").text()));$("#"+b+"freg1_10").val(parseInt(a.find("Resistance11").text()));$("#"+b+"freg1_11").val(parseInt(a.find("Resistance12").text()));$("#"+b+"freg1_12").val(parseInt(a.find("Resistance13").text()));$("#"+b+"freg1_13").val(parseInt(a.find("Resistance14").text()));$("#"+b+"freg2_0").val(x);$("#"+b+"freg2_1").val(y);$("#"+b+"freg2_2").val(z);$("#"+b+"freg2_3").val(A);$("#"+b+"freg2_4").val(B);$("#"+b+"freg2_5").val(C);$("#"+b+"freg2_6").val(D);
$("#"+b+"freg2_7").val(E);$("#"+b+"freg2_8").val(F);$("#"+b+"freg2_9").val(G);$("#"+b+"freg2_10").val(H);$("#"+b+"freg2_11").val(I);$("#"+b+"freg2_12").val(J);$("#"+b+"freg2_13").val(K)}
function SetString(b){for(var c=0;c<b;c++)$("#tmain"+c+"type0").text("\u7a2e\u65cf"),$("#tmain"+c+"type1").text("\u7cfb\u7d71"),$("#tmain"+c+"abbility1_0").text("HP"),$("#tmain"+c+"abbility1_1").text("\u653b\u6483\u529b"),$("#tmain"+c+"abbility1_2").text("\u9632\u5fa1\u529b"),$("#tmain"+c+"abbility2_0").text("\u653b\u6483\u901f\u5ea6"),$("#tmain"+c+"abbility2_1").text("\u79fb\u52d5\u901f\u5ea6"),$("#tmain"+c+"abbility2_2").text("\u30d6\u30ed\u30c3\u30af\u7387"),$("#tmain"+c+"abbility2_3").text("\u30a2\u30af\u30c6\u30a3\u30d6\u5c04\u7a0b"),
$("#tmain"+c+"abbility2_4").text("\u57fa\u790e\u7d4c\u9a13\u5024"),$("#tmain"+c+"status0").text("\u529b"),$("#tmain"+c+"status1").text("\u654f\u6377"),$("#tmain"+c+"status2").text("\u5065\u5eb7"),$("#tmain"+c+"status3").text("\u77e5\u8b58"),$("#tmain"+c+"status4").text("\u77e5\u6075"),$("#tmain"+c+"status5").text("\u5a01\u53b3"),$("#tmain"+c+"status6").text("\u904b"),$("#tmain"+c+"ereg0").text("\u706b"),$("#tmain"+c+"ereg1").text("\u6c34"),$("#tmain"+c+"ereg2").text("\u98a8"),$("#tmain"+c+"ereg3").text("\u571f"),
$("#tmain"+c+"ereg4").text("\u5149"),$("#tmain"+c+"ereg5").text("\u95c7"),$("#tmain"+c+"reg1_0").text("\u6697\u95c7"),$("#tmain"+c+"reg1_1").text("\u6bd2"),$("#tmain"+c+"reg1_2").text("\u7761\u7720"),$("#tmain"+c+"reg1_3").text("\u30b3\u30fc\u30eb\u30c9"),$("#tmain"+c+"reg1_4").text("\u30d5\u30ea\u30fc\u30ba"),$("#tmain"+c+"reg1_5").text("\u30b9\u30bf\u30f3"),$("#tmain"+c+"reg1_6").text("\u77f3\u5316"),$("#tmain"+c+"reg1_14").text("\u6df7\u4e71"),$("#tmain"+c+"reg1_15").text("\u9b45\u4e86"),$("#tmain"+
c+"reg1_16").text("\u7570\u5e38"),$("#tmain"+c+"reg1_17").text("\u4f4e\u4e0b"),$("#tmain"+c+"reg1_18").text("\u546a\u3044"),$("#tmain"+c+"reg1_19").text("\u81f4\u547d\u6253"),$("#tmain"+c+"reg1_20").text("\u6c7a\u5b9a\u6253"),$("#tmain"+c+"reg2_0").text("\u6697\u95c7"),$("#tmain"+c+"reg2_1").text("\u6bd2"),$("#tmain"+c+"reg2_2").text("\u7761\u7720"),$("#tmain"+c+"reg2_3").text("\u30b3\u30fc\u30eb\u30c9"),$("#tmain"+c+"reg2_4").text("\u30d5\u30ea\u30fc\u30ba"),$("#tmain"+c+"reg2_5").text("\u30b9\u30bf\u30f3"),
$("#tmain"+c+"reg2_6").text("\u77f3\u5316"),$("#tmain"+c+"reg2_14").text("\u6df7\u4e71"),$("#tmain"+c+"reg2_15").text("\u9b45\u4e86"),$("#tmain"+c+"reg2_16").text("\u7570\u5e38"),$("#tmain"+c+"reg2_17").text("\u4f4e\u4e0b"),$("#tmain"+c+"reg2_18").text("\u546a\u3044"),$("#tmain"+c+"reg2_19").text("\u81f4\u547d\u6253"),$("#tmain"+c+"reg2_20").text("\u6c7a\u5b9a\u6253")}
function CreateTable(b){for(var c=$("<div />"),a=0;a<b;a++){var e="tmain"+a,d=$("<table />"),l=$("<tr />");l.append($("<th />").attr("id",e+"name").addClass("title"));l.append($("<th />").attr({rowspan:"7",colspan:"2"}).css({"background-color":"#000000"}).append($("<div />").attr("id",e+"image")));var i=$("<tr />");i.append($("<td />").attr({id:e+"lv",title:"Lv\u3092\u5909\u66f4\u3059\u308b\u3068\u80fd\u529b\u5024\u304c\u66f4\u65b0\u3055\u308c\u307e\u3059\u3002"}).text("\u5165\u529bLv: ").append($("<input />").attr({id:e+
"flv",name:"",type:"text",value:"200"}).addClass("inputlvform").css("width","100px").bind("keyup",function(){var a=$(this).attr("id"),a=a.substr(0,a.length-3);StatusUpdate(a,$(this).attr("name"))})));var h=$("<tr />");h.append($("<td />").attr("id",e+"type").append(CreateSubTable(a,"type",2,2)));var j=$("<tr />");j.append($("<td />").attr("id",e+"abbility1_").append(CreateSubTable(a,"abbility1_",2,3)));var k=$("<tr />");k.append($("<td />").attr("id",e+"abbility2_").append(CreateSubTable(a,"abbility2_",
2,5)));var m=$("<tr />");m.append($("<td />").attr("id",e+"status").append($("<div />").css({margin:"3px 0 0 5px","text-align":"left","vertical-align":"top"}).text("<\u57fa\u790e\u80fd\u529b\u5024> (Lv\u5165\u529b\u5bfe\u5fdc)")).append(CreateSubTable(a,"status",2,7)));var f=$("<tr />");f.append($("<td />").attr("id",e+"ereg").append($("<div />").css({margin:"3px 0 0 5px","text-align":"left","vertical-align":"top"}).text("<\u5143\u7d20\u62b5\u6297\u5024> (Lv\u5165\u529b\u5bfe\u5fdc)")).append(CreateSubTable(a,
"ereg",2,6)));var g=$("<tr />");g.append($("<td />").attr("id",e+"reg1").append($("<div />").css({margin:"3px 0 0 5px","text-align":"left","vertical-align":"top"}).text("<\u57fa\u790e\u62b5\u6297\u5024>")).append(CreateSubTable(a,"reg1_",4,7)));g.append($("<td />").attr({id:e+"skill",rowspan:"2"}).css({padding:"3px 0 0 5px","text-align":"left","vertical-align":"top"}).text("<\u4f7f\u7528\u30b9\u30ad\u30eb>"));g.append($("<td />").attr({id:e+"dtype",rowspan:"2"}).css({padding:"3px 0 0 5px","text-align":"left",
"vertical-align":"top"}).text("<Drop\u30a2\u30a4\u30c6\u30e0>"));var n=$("<tr />");n.append($("<td />").attr("id",e+"reg2").append($("<div />").css({margin:"3px 0 0 5px","text-align":"left","vertical-align":"top"}).text("<\u6700\u7d42\u62b5\u6297\u5024> (Lv\u5165\u529b\u5bfe\u5fdc)")).append(CreateSubTable(a,"reg2_",4,7)));d.addClass("mobtable").attr("id",e).css({display:"none"});d.append(l);d.append(i);d.append(h);d.append(j);d.append(k);d.append(m);d.append(f);d.append(g);d.append(n);c.append(d)}$("#m_result").empty().append(c)}
function CreateSubTable(b,c,a,e){for(var d=0,l=$("<table />"),i=0;i<a;i++){for(var h=$("<tr />"),j=0;j<e;j++){var k="tmain"+b+c+(j+i*e),k=$("<div />").attr("id",k),m=$("<td />");if(0==i%2)m.css("background-color","#505050");else{var f="",g="5px",n=$("<input />");"type"===c&&(f="tmain"+b+"fty"+d++,g="190px");"abbility1_"===c&&(f="tmain"+b+"fab1_"+d++,g="120px");"abbility2_"===c&&(f="tmain"+b+"fab2_"+d++,g="75px");"status"===c&&(f="tmain"+b+"fst"+d++,g="45px");"ereg"===c&&(f="tmain"+b+"fel"+d++,g="55px");
"reg1_"===c&&(f="tmain"+b+"freg1_"+d++,g="45px");"reg2_"===c&&(f="tmain"+b+"freg2_"+d++,g="45px");n.attr({id:f,type:"text",readonly:""}).addClass("inputform").css("width",g);k.append(n)}m.append(k);h.append(m)}l.append(h)}l.addClass("subtable");return l}
function CreatepIndex(b,c){var a=ResultAry.length%ContentDisplayCount,e=(ResultAry.length-a)/ContentDisplayCount;0!=a&&(e+=1);a=$("<div />");a.append($("<table />").append(function(){for(var a=$("<tr />"),b=0;b<e;b++){var i=$("<td />"),h=$("<div />"),j=$("<a />");b!=c?(j.attr({href:"#pagetop"}).text(b+1).click(function(){DisplayDataAry($(this).text()-1)}),h.append(j)):h.text(b+1);h.css("margin","0 2px");a.append(i.append(h))}return a}));a.addClass("pindex");$("#"+b).empty().append(a);return e};