var iList=null,ResultAry=[],Mode=null,KeyWord="",ContentDisplayCount=20,ContentCount=50,AddinfoCount=10,CreateCount=1;function createXMLHttpRequest(d){var c=null;try{c=new XMLHttpRequest}catch(g){try{c=new ActiveXObject("Msxml2.XMLHTTP")}catch(b){try{c=new ActiveXObject("Microsoft.XMLHTTP")}catch(f){return null}}}c&&(c.onreadystatechange=d);return c}function $(d){return document.getElementById(d)}
window.onload=function(){if(httpObj=createXMLHttpRequest(LoadingData))httpObj.open("GET","ItemList.xml",!0),httpObj.send(null)};function LoadingData(){4==httpObj.readyState&&200==httpObj.status?(iList=httpObj.responseXML.getElementsByTagName("item"),$("status").innerHTML='<font color="#FFFFFF">OK</font>',Getparam(),SearchOfKeyword(Mode),DisplayDataAry(!0,0)):$("status").innerHTML='<font color="#FFFFFF">Now Loading...</font>'}
function Getparam(){var d=location.search;if(!d)return!1;for(var d=d.substring(1),d=d.split("&"),c="",g=[],b=0;b<d.length;b++)c=d[b].split("="),keyName=c[0],keyValue=c[1],g[keyName]=keyValue;g.Mode&&""!=g.Mode&&(Mode=decodeURI(g.Mode));g.keyword&&""!=g.keyword&&(KeyWord=decodeURI(g.keyword))}
function SearchOfKeyword(d){ResultAry.length=0;if(1==d){if(d=KeyWord,d.length)for(var c=0,g=0;g<iList.length;g++){var b=iList[g].getElementsByTagName("itemType"),f=-1;b[0].hasChildNodes()&&(f=b[0].childNodes[0].nodeValue,f==d&&(ResultAry[c++]=g))}}else if(2==d){if(d=KeyWord,d.length)for(g=c=0;g<iList.length;g++)b=iList[g].getElementsByTagName("itemName"),f="",b[0].hasChildNodes()&&(f=b[0].childNodes[0].nodeValue,-1!=f.indexOf(d,0)&&(ResultAry[c++]=g))}else if(3==d){if(d=document.searchform1.keyword.value,
d.length)for(g=c=0;g<iList.length;g++)b=iList[g].getElementsByTagName("itemName"),b[0].hasChildNodes()&&(f=b[0].childNodes[0].nodeValue,-1!=f.indexOf(d,0)&&(ResultAry[c++]=g))}else if(4==d&&(d=KeyWord,d.length))for(g=c=0;g<iList.length;g++){f=[];f.push(iList[g].getElementsByTagName("OpPrt1"));f.push(iList[g].getElementsByTagName("OpPrt2"));f.push(iList[g].getElementsByTagName("OpPrt3"));f.push(iList[g].getElementsByTagName("OpPrt4"));f.push(iList[g].getElementsByTagName("OpBit1"));f.push(iList[g].getElementsByTagName("OpBit2"));
f.push(iList[g].getElementsByTagName("OpBit3"));f.push(iList[g].getElementsByTagName("OpBit4"));f.push(iList[g].getElementsByTagName("OpBit5"));f.push(iList[g].getElementsByTagName("OpBit6"));f.push(iList[g].getElementsByTagName("OpNxt1"));f.push(iList[g].getElementsByTagName("OpNxt2"));f.push(iList[g].getElementsByTagName("OpNxt3"));f.push(iList[g].getElementsByTagName("OpNxt4"));for(var a=0;a<f.length;a++){var b=f[a],h="";if(b[0].hasChildNodes()&&(h=b[0].childNodes[0].nodeValue,-1!=h.indexOf(d,
0))){ResultAry[c++]=g;break}}}}function DisplayData(d,c,g){CreateTable(d);itemNumber=c;for(d=0;d<CreateCount;d++,itemNumber++)SettingData(itemNumber,d,g)}
function DisplayDataAry(d,c){var g,b;CreatepIndex("pheader",c);CreatepIndex("pfooter",c);CreateTable(ContentDisplayCount);if(ResultAry.length){g=c*ContentDisplayCount+1;for(var f=0;f<ContentDisplayCount;f++){var a=f+c*ContentDisplayCount;a<ResultAry.length&&(b=a+1,SettingData(ResultAry[a],f,d))}$("s_result").innerHTML=ResultAry.length+"\u4ef6\u306e\u30a2\u30a4\u30c6\u30e0\u304c\u8a72\u5f53\u3057\u307e\u3057\u305f\u3002  "+g+"\u4ef6\u76ee\u304b\u3089"+b+"\u4ef6\u76ee\u307e\u3067\u306e\u8868\u793a"}else $("s_result").innerHTML=
"\u8a72\u5f53\u30a2\u30a4\u30c6\u30e0\u304c\u3042\u308a\u307e\u305b\u3093\u3067\u3057\u305f\u3002"}
function SettingData(d,c,g){var b,f,a;a="";var h=!1,j=!1;$("tmain"+c).style.display="block";b=iList[d].getElementsByTagName("itemType");var e=-1;b[0].hasChildNodes()&&(e=b[0].childNodes[0].nodeValue);b=iList[d].getElementsByTagName("isU");var i=0;b[0].hasChildNodes()&&(i=b[0].childNodes[0].nodeValue);b=iList[d].getElementsByTagName("isDX");var l=0;b[0].hasChildNodes()&&(l=b[0].childNodes[0].nodeValue);b=iList[d].getElementsByTagName("isUM");var n=0;b[0].hasChildNodes()&&(n=b[0].childNodes[0].nodeValue);
b=iList[d].getElementsByTagName("isEX");var p=0;b[0].hasChildNodes()&&(p=b[0].childNodes[0].nodeValue);b=iList[d].getElementsByTagName("isNX");var m=0;b[0].hasChildNodes()&&(m=b[0].childNodes[0].nodeValue);b=iList[d].getElementsByTagName("itemExRank");f=0;b[0].hasChildNodes()&&(f=b[0].childNodes[0].nodeValue);b=iList[d].getElementsByTagName("itemImageId");var k="";b[0].hasChildNodes()&&(k=b[0].childNodes[0].nodeValue,k="ItemImage/"+k+".png",$("c"+c+"trtip0").style.display="block",a="c"+c+"trtip0resultitemimg",
$(a).className="img_item",$(a).style.display="block",$(a).margin="2px 0 8px 2px",$(a).setAttribute("src",k),$(a).style.width="34px",$(a).style.height="34px");b=iList[d].getElementsByTagName("itemName");k="";b[0].hasChildNodes()&&(k=b[0].childNodes[0].nodeValue,a="c"+c+"trtip1",$(a).style.display="block",$(a).style.paddingTop="5px",$(a).setAttribute("title",d));b=!1;1==l&&!b&&(b="Interface/DX.gif",a="c"+c+"trtip0resultigradeimg",$(a).className="img_igrade",$(a).style.display="block",$(a).setAttribute("src",
b),$(a).style.width="15px",$(a).style.height="9px",b=!0);1==n&&!b&&(b="Interface/UM.gif",a="c"+c+"trtip0resultigradeimg",$(a).className="img_igrade",$(a).style.display="block",$(a).setAttribute("src",b),$(a).style.width="15px",$(a).style.height="9px");b=!1;1==m&&!b&&(m="Interface/NX.gif",a="c"+c+"trtip0resultitypeimg",$(a).className="img_itype",$(a).style.display="block",$(a).setAttribute("src",m),$(a).style.width="13px",$(a).style.height="11px",""!=k&&(k='<font color="#800000">'+k+"</font>",b=!0));
1==i&&!b&&(m="Interface/U.gif",a="c"+c+"trtip0resultitypeimg",$(a).className="img_itype",$(a).style.display="block",$(a).setAttribute("src",m),$(a).style.width="9px",$(a).style.height="9px",""!=k&&(k='<font color="#E8C898">'+k+"</font>",b=!0));1==p&&!b&&(i=a="",-1!=f&&(0==f&&(a="Ex10",i="Rank10"),1==f&&(a="Ex9",i="Rank9"),2==f&&(a="Ex8",i="Rank8"),3==f&&(a="Ex7",i="Rank7"),4==f&&(a="Ex6",i="Rank6"),5==f&&(a="Ex5",i="Rank5"),6==f&&(a="Ex4",i="Rank4"),7==f&&(a="Ex3",i="Rank3"),8==f&&(a="Ex2",i="Rank2"),
9==f&&(a="Ex1",i="Rank1"),10==f&&(a="ExP",i="\u7279\u7b49"),11==f&&(a="ExA",i="\u6700\u4e0a"),12==f&&(a="ExU",i="\u81f3\u9ad8"),$("c"+c+"trtip5").style.display="block",$("c"+c+"trtip5result").innerHTML='- <font color="#F8F800">'+i+"</font> \u30a8\u30ad\u30b9\u30c8\u30e9\u30a2\u30a4\u30c6\u30e0",m="Interface/"+a+".gif",a="c"+c+"trtip0resultitypeimg",$(a).className="img_itype",$(a).style.display="block",$(a).setAttribute("src",m),$(a).style.width="13px",$(a).style.height="11px",""!=k&&(k='<font color="#B2B2F8">'+
k+"</font>",b=!0)));49==e&&!b&&(m="Interface/Q.gif",a="c"+c+"trtip0resultitypeimg",$(a).className="img_itype",$(a).style.display="block",$(a).setAttribute("src",m),$(a).style.width="9px",$(a).style.height="9px");""!=k&&($("c"+c+"trtip1result").innerHTML=k);b=iList[d].getElementsByTagName("Description");e="";b[0].hasChildNodes()&&(e=b[0].childNodes[0].nodeValue,$("c"+c+"trtip40").style.display="block",a="c"+c+"trtip40result",$(a).style.paddingTop="5px",$(a).innerHTML='<font color="#00F8F8">&lt;\u8aac\u660e&gt;</font>',
$("c"+c+"trtip41").style.display="block",$("c"+c+"trtip41result").innerHTML="- "+e);b=iList[d].getElementsByTagName("AbilityDemand");e="";b[0].hasChildNodes()&&(e=b[0].childNodes[0].nodeValue,$("c"+c+"trtip42").style.display="block",a="c"+c+"trtip42result",$(a).style.paddingTop="5px",$(a).innerHTML='<font color="#00F8F8">&lt;\u8981\u6c42\u80fd\u529b\u5024&gt;</font>',$("c"+c+"trtip43").style.display="block",$("c"+c+"trtip43result").innerHTML=e);b=iList[d].getElementsByTagName("EquipmentJobType");
e="";b[0].hasChildNodes()&&(e=b[0].childNodes[0].nodeValue,$("c"+c+"trtip44").style.display="block",a="c"+c+"trtip44result",$(a).style.paddingTop="5px",$(a).innerHTML='<font color="#00F8F8">&lt;\u7740\u7528/\u4f7f\u7528\u53ef\u80fd\u306a\u8077\u696d&gt;</font>',$("c"+c+"trtip45").style.display="block",$("c"+c+"trtip45result").innerHTML=e);b=iList[d].getElementsByTagName("AtParameter");b[0].hasChildNodes()&&(k=!1,f=b[0].getElementsByTagName("AtRange"),a=0,f[0].hasChildNodes()&&(a=f[0].childNodes[0].nodeValue,
0!=a&&(h=!0,$("c"+c+"trtip9").style.display="block",$("c"+c+"trtip9result").innerHTML='- \u5c04\u7a0b\u8ddd\u96e2 <font color="#F8F800">'+a+"</font>")),f=b[0].getElementsByTagName("AtSpeed"),a=0,f[0].hasChildNodes()&&(a=f[0].childNodes[0].nodeValue,0!=a&&(k=h=!0)),f=b[0].getElementsByTagName("AtMaxValue"),e=0,f[0].hasChildNodes()&&(e=f[0].childNodes[0].nodeValue,0!=e&&(k=h=!0)),f=b[0].getElementsByTagName("AtMinValue"),b=0,f[0].hasChildNodes()&&(b=f[0].childNodes[0].nodeValue,0!=b&&(k=h=!0)),!0==
k&&(k=f="",f='- \u653b\u6483\u529b <font color="#F8F800">'+b+"~"+e+"</font>",0!=a&&(k='(<font color="#F8F800">'+a+"</font>\u79d2)"),$("c"+c+"trtip10").style.display="block",$("c"+c+"trtip10result").innerHTML=f+k));b=iList[d].getElementsByTagName("OpParameter");b[0].hasChildNodes()&&(a=b[0].getElementsByTagName("OpPrt1"),e="",a[0].hasChildNodes()&&(e=a[0].childNodes[0].nodeValue,e="- "+e,h=!0,$("c"+c+"trtip15").style.display="block",$("c"+c+"trtip15result").innerHTML=e),a=b[0].getElementsByTagName("OpPrt2"),
e="",a[0].hasChildNodes()&&(e=a[0].childNodes[0].nodeValue,e="- "+e,h=!0,$("c"+c+"trtip16").style.display="block",$("c"+c+"trtip16result").innerHTML=e),a=b[0].getElementsByTagName("OpPrt3"),e="",a[0].hasChildNodes()&&(e=a[0].childNodes[0].nodeValue,e="- "+e,h=!0,$("c"+c+"trtip17").style.display="block",$("c"+c+"trtip17result").innerHTML=e),a=b[0].getElementsByTagName("OpPrt4"),e="",a[0].hasChildNodes()&&(e=a[0].childNodes[0].nodeValue,e="- "+e,h=!0,$("c"+c+"trtip18").style.display="block",$("c"+c+
"trtip18result").innerHTML=e),a=b[0].getElementsByTagName("MiniPetFoodType"),e="",a[0].hasChildNodes()&&(e=a[0].childNodes[0].nodeValue,e='- \u30df\u30cb\u30da\u30c3\u30c8\u30a8\u30b5\u5206\u985e <font color="#F8F800">'+e+"</font>",h=!0,$("c"+c+"trtip19").style.display="block",$("c"+c+"trtip19result").innerHTML=e),a=b[0].getElementsByTagName("ExpirationDate"),e="",a[0].hasChildNodes()&&(e=a[0].childNodes[0].nodeValue,e='- \u6709\u52b9\u671f\u9650 <font color="#F8F800">'+e+"</font>",h=!0,$("c"+c+"trtip20").style.display=
"block",$("c"+c+"trtip20result").innerHTML=e),a=b[0].getElementsByTagName("OpBit1"),e="",a[0].hasChildNodes()&&(e=a[0].childNodes[0].nodeValue,e="- "+e,h=!0,$("c"+c+"trtip21").style.display="block",$("c"+c+"trtip21result").innerHTML=e),a=b[0].getElementsByTagName("OpBit2"),e="",a[0].hasChildNodes()&&(e=a[0].childNodes[0].nodeValue,e="- "+e,h=!0,$("c"+c+"trtip22").style.display="block",$("c"+c+"trtip22result").innerHTML=e),a=b[0].getElementsByTagName("OpBit3"),e="",a[0].hasChildNodes()&&(e=a[0].childNodes[0].nodeValue,
e="- "+e,h=!0,$("c"+c+"trtip23").style.display="block",$("c"+c+"trtip23result").innerHTML=e),a=b[0].getElementsByTagName("OpBit4"),e="",a[0].hasChildNodes()&&(e=a[0].childNodes[0].nodeValue,e="- "+e,h=!0,$("c"+c+"trtip24").style.display="block",$("c"+c+"trtip24result").innerHTML=e),a=b[0].getElementsByTagName("OpBit5"),e="",a[0].hasChildNodes()&&(e=a[0].childNodes[0].nodeValue,e="- "+e,h=!0,$("c"+c+"trtip25").style.display="block",$("c"+c+"trtip25result").innerHTML=e),a=b[0].getElementsByTagName("OpBit6"),
e="",a[0].hasChildNodes()&&(e=a[0].childNodes[0].nodeValue,e="- "+e,h=!0,$("c"+c+"trtip26").style.display="block",$("c"+c+"trtip26result").innerHTML=e),!0==h&&($("c"+c+"trtip3").style.display="block",a="c"+c+"trtip3result",$(a).style.paddingTop="5px",$(a).innerHTML='<font color="#00F8F8">&lt;\u57fa\u672c\u60c5\u5831&gt;</font>',a=b[0].getElementsByTagName("isNotTrade"),h="",a[0].hasChildNodes()&&(h=a[0].childNodes[0].nodeValue,h='- <font color="#D080F8">'+h+"</font>",$("c"+c+"trtip4").style.display=
"block",$("c"+c+"trtip4result").innerHTML=h)),a=b[0].getElementsByTagName("OpNxt1"),h="",a[0].hasChildNodes()&&(h=a[0].childNodes[0].nodeValue,h="- "+h,j=!0,$("c"+c+"trtip31").style.display="block",$("c"+c+"trtip31result").innerHTML=h),a=b[0].getElementsByTagName("OpNxt2"),h="",a[0].hasChildNodes()&&(h=a[0].childNodes[0].nodeValue,h="- "+h,j=!0,$("c"+c+"trtip32").style.display="block",$("c"+c+"trtip32result").innerHTML=h),a=b[0].getElementsByTagName("OpNxt3"),h="",a[0].hasChildNodes()&&(h=a[0].childNodes[0].nodeValue,
h="- "+h,j=!0,$("c"+c+"trtip33").style.display="block",$("c"+c+"trtip33result").innerHTML=h),a=b[0].getElementsByTagName("OpNxt4"),b="",a[0].hasChildNodes()&&(b=a[0].childNodes[0].nodeValue,b="- "+b,j=!0,$("c"+c+"trtip34").style.display="block",$("c"+c+"trtip34result").innerHTML=b),!0==j&&($("c"+c+"trtip30").style.display="block",a="c"+c+"trtip30result",$(a).style.paddingTop="5px",$(a).innerHTML='<font color="#00F8F8">&lt;\u932c\u6210 \u30aa\u30d7\u30b7\u30e7\u30f3 \u60c5\u5831&gt;</font>'));!0==
g&&($("addinfo"+c).style.display="block");b=iList[d].getElementsByTagName("AddInformation");b[0].hasChildNodes()&&(d=b[0].getElementsByTagName("StackSize"),g=0,$("c"+c+"traddinfo0").style.display="block",d[0].hasChildNodes()&&(g=d[0].childNodes[0].nodeValue,$("c"+c+"traddinfo0result").innerHTML=g),d=b[0].getElementsByTagName("DecreasedEnduranceType"),g=0,$("c"+c+"traddinfo1").style.display="block",d[0].hasChildNodes()&&(g=d[0].childNodes[0].nodeValue,$("c"+c+"traddinfo1result").innerHTML=g+"\u578b"),
d=b[0].getElementsByTagName("DropLevel"),g=0,$("c"+c+"traddinfo2").style.display="block",d[0].hasChildNodes()&&(g=d[0].childNodes[0].nodeValue,$("c"+c+"traddinfo2result").innerHTML=g),d=b[0].getElementsByTagName("DropFactor"),g=0,$("c"+c+"traddinfo3").style.display="block",d[0].hasChildNodes()&&(g=d[0].childNodes[0].nodeValue,$("c"+c+"traddinfo3result").innerHTML=g),d=b[0].getElementsByTagName("PriceType"),g="",d[0].hasChildNodes()&&(g=d[0].childNodes[0].nodeValue),d=b[0].getElementsByTagName("PriceAddParam"),
j=0,d[0].hasChildNodes()&&(j=d[0].childNodes[0].nodeValue),d=b[0].getElementsByTagName("Price"),h=0,$("c"+c+"traddinfo4").style.display="block",$("c"+c+"traddinfo5").style.display="block",d[0].hasChildNodes()&&(h=d[0].childNodes[0].nodeValue,$("c"+c+"traddinfo4result").innerHTML=h+"G",""==g&&(g="\u7d14\u4fa1\u683c"),0!=j&&(g=g+" * "+j+"%"),$("c"+c+"traddinfo5result").innerHTML=g),d=b[0].getElementsByTagName("itemProperty"),g="",$("c"+c+"traddinfo6").style.display="block",d[0].hasChildNodes()&&(g=
d[0].childNodes[0].nodeValue,$("c"+c+"traddinfo6result").innerHTML=g))}
function CreateTable(d){var c=document.createElement("div");CreateCount=d;for(d=0;d<CreateCount;d++){var g=document.createElement("table"),b=document.createElement("tbody"),f=document.createElement("tr"),a=document.createElement("td"),h=document.createElement("td"),j=document.createElement("div"),e=document.createElement("div"),i=document.createElement("table"),l=document.createElement("tbody"),n=document.createElement("tr"),p=document.createElement("tr"),m=document.createElement("tr"),k=document.createElement("td"),
r=document.createElement("td"),s=document.createElement("td"),t=document.createElement("td"),q=document.createElement("td"),u=document.createElement("td"),v=document.createElement("td"),w=document.createElement("td"),x=document.createElement("td"),y="addinfo"+d,z="tmain"+d;k.className="top_left";r.className="top";s.className="top_right";t.className="left";q.className="content";CreateContent(q,d);u.className="right";v.className="bottom_left";w.className="bottom";x.className="bottom_right";n.appendChild(k);
n.appendChild(r);n.appendChild(s);p.appendChild(t);p.appendChild(q);p.appendChild(u);m.appendChild(v);m.appendChild(w);m.appendChild(x);l.appendChild(n);l.appendChild(p);l.appendChild(m);i.style.width="320px";i.appendChild(l);j.appendChild(i);j.className="tooltip";e.id=y;e.className="addinfo";e.style.display="none";CreateAddInfo(e,d);a.appendChild(j);h.appendChild(e);f.appendChild(a);f.appendChild(h);b.appendChild(f);g.appendChild(b);g.id=z;g.className="tiptable";g.style.display="none";c.appendChild(g)}$("tooltip").hasChildNodes()&&
(d=$("tooltip"),d.removeChild(d.firstChild));$("tooltip").appendChild(c)}
function CreateContent(d,c){for(var g=document.createElement("table"),b=document.createElement("tbody"),f=0;f<ContentCount;f++){var a=document.createElement("tr"),h=document.createElement("td"),j=document.createElement("div"),e=document.createElement("img"),i=document.createElement("img"),l=document.createElement("img"),n="c"+c+"trtip"+f,p=n+"result";a.id=n;a.style.display="none";j.id=p;0==f&&(e.id=p+"itemimg",e.setAttribute("src",""),e.setAttribute("alt","none"),e.style.display="none",i.id=p+"itypeimg",
i.setAttribute("src",""),i.setAttribute("alt",""),i.style.display="none",l.id=p+"igradeimg",l.setAttribute("src",""),l.setAttribute("alt",""),l.style.display="none",j.style.position="relative",j.appendChild(e),j.appendChild(i),j.appendChild(l));h.appendChild(j);a.appendChild(h);b.appendChild(a)}g.appendChild(b);d.appendChild(g)}
function CreateAddInfo(d,c){for(var g=document.createElement("table"),b=document.createElement("tbody"),f=0;f<AddinfoCount;f++){var a=document.createElement("tr"),h=document.createElement("th"),j=document.createElement("td"),e=document.createElement("div"),i=document.createElement("div"),l="c"+c+"traddinfo"+f,n=l+"result";0==f&&i.appendChild(document.createTextNode("\u91cd\u306d\u7f6e\u304d\u53ef\u80fd\u500b\u6570"));1==f&&i.appendChild(document.createTextNode("\u8010\u4e45\u6e1b\u5c11\u578b\u5f0f"));
2==f&&i.appendChild(document.createTextNode("DropLevel"));3==f&&i.appendChild(document.createTextNode("Drop\u4fc2\u6570"));4==f&&i.appendChild(document.createTextNode("\u7d14\u4fa1\u683c"));5==f&&i.appendChild(document.createTextNode("\u4fa1\u683c\u8a08\u7b97\u5f0f"));6==f&&i.appendChild(document.createTextNode("\u30a2\u30a4\u30c6\u30e0\u7279\u6027"));7==f&&i.appendChild(document.createTextNode("none"));8==f&&i.appendChild(document.createTextNode("none"));i.style.margin="2px 10px 2px 0";h.appendChild(i);
a.id=l;a.style.display="none";e.id=n;e.style.margin="0 20px";j.appendChild(e);a.appendChild(h);a.appendChild(j);b.appendChild(a)}g.appendChild(b);d.appendChild(g)}
function CreatepIndex(d,c){var g=ResultAry.length%ContentDisplayCount,b=(ResultAry.length-g)/ContentDisplayCount;0!=g&&(b+=1);for(var g=document.createElement("div"),f=document.createElement("table"),a=document.createElement("tbody"),h=document.createElement("tr"),j=0;j<b;j++){var e=document.createElement("td"),i=document.createElement("div"),l=document.createElement("a");l.setAttribute("href","#pagetop");j!=c?(l.onclick=function(){DisplayDataAry(!0,this.childNodes[0].nodeValue-1)},l.appendChild(document.createTextNode(j+
1)),i.appendChild(l)):i.appendChild(document.createTextNode(j+1));i.style.margin="0 2px";e.appendChild(i);h.appendChild(e)}a.appendChild(h);f.appendChild(a);g.appendChild(f);g.className="pindex";$(d).hasChildNodes()&&(f=$(d),f.removeChild(f.firstChild));$(d).appendChild(g);return b};